apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-new-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: nginx
      labels:
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
