apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica-set
  labels:
    app: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      name: nginx
      labels:
        app: frontend-deployment
    spec:
      containers:
        - name: nginx
          image: nginx
